### PR TITLE
Add installation docs

### PR DESCRIPTION
**Pull request by guineveresaenger**
Part of pulumi/home#3598

Generates a single index.md file with relevant content.

- **Add automation**
- **Add an HTML comment below each table to ensure it renders. Fixup HCL so we can translate the given example.**

### CODE REVIEW

**Review by iwahbe — COMMENTED** [review]
How does the table display in the registry?

**Comment by guineveresaenger** [comment]
Here's a screenshot. It's Not Great due to GFMD being weird about code blocks inside table elements.

It might be worth it to wait and fix #2446 first. 

It's Not Awesome, because also 
Screenshot 2024-10-24 at 12 38 01 PM

**Comment by guineveresaenger** [comment]
Now the table renders better, and there's no need for hacks.

[7f6e5c1](https://github.com/pulumi/pulumi-newrelic/pull/890/commits/7f6e5c1ebf4a699a59e1f281e655a1206e83a8fe) is based on https://github.com/pulumi/pulumi-terraform-bridge/pull/2603, so we're still blocked until the changes are accepted.


Screenshot 2024-11-07 at 5 07 42 PM

**Review by blampe — APPROVED** [review]
Nice!

**Pull request merged**
